////////////////////////////////////////////
///        generated by deepseek         ///
////////////////////////////////////////////


const list_el    = document.getElementById("list");
const summary_el = document.getElementById("summary");
const empty_el   = document.getElementById("empty");
const clear_btn  = document.getElementById("clear");

/** 把 file:///C:/a/b.html 显示成 b.html */
function url_label(url) {
    try {
        const path = decodeURIComponent(new URL(url).pathname);
        return path.substring(path.lastIndexOf("/") + 1) || path;
    } catch {
        return url;
    }
}

/** 只取本扩展自己写的记录（key 是 url，value 是数字百分比） */
async function load_records() {
    const all = await chrome.storage.local.get(null);
    return Object.entries(all)
        .filter(([url, value]) => typeof value === "number" && /^file:/i.test(url))
        .map(([url, pos]) => ({ url, pos }))
        .sort((a, b) => a.url.localeCompare(b.url));
}

function render(records) {
    list_el.textContent = "";
    summary_el.textContent = records.length ? `${records.length} 条` : "";
    empty_el.hidden = records.length > 0;

    for (const { url, pos } of records) {
        const li = document.createElement("li");

        const name = document.createElement("span");
        name.className = "name";
        name.textContent = url_label(url);
        name.title = url;                       // 悬停看完整路径

        const pct = document.createElement("span");
        pct.className = "pct";
        pct.textContent = pos.toFixed(1) + "%";

        const del = document.createElement("button");
        del.className = "del";
        del.textContent = "✕";
        del.title = "删除这一条";
        del.addEventListener("click", async () => {
            await chrome.storage.local.remove(url);
            refresh();
        });

        li.append(name, pct, del);
        list_el.append(li);
    }
}

async function refresh() {
    render(await load_records());
}

/* ---- 清空全部：两次点击确认，避免用 alert/confirm 把弹窗顶掉 ---- */
let armed = false;
let arm_timer = 0;

function disarm() {
    armed = false;
    clearTimeout(arm_timer);
    clear_btn.classList.remove("armed");
    clear_btn.textContent = "清空全部";
}

clear_btn.addEventListener("click", async () => {
    if (!armed) {
        armed = true;
        clear_btn.classList.add("armed");
        clear_btn.textContent = "再点一次确认";
        arm_timer = setTimeout(disarm, 3000);
        return;
    }

    const records = await load_records();
    disarm();

    if (records.length === 0) { return; }
    // 只删自己的 key，不影响 storage 里可能存在的其他数据
    await chrome.storage.local.remove(records.map(r => r.url));
    refresh();
});

/* 弹窗开着时，如果后台又写了新位置，自动刷新 */
chrome.storage.onChanged.addListener((changes, area) => {
    if (area === "local") { refresh(); }
});

refresh();